"""Modes table

Revision ID: 1fd4714f1db2
Revises: b149855c1067
Create Date: 2018-09-05 08:48:35.417424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd4714f1db2'
down_revision = 'b149855c1067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode',
    sa.Column('view', sa.Boolean(), nullable=False),
    sa.Column('edit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('view')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mode')
    # ### end Alembic commands ###
